name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # - name : dddd
    #   run: echo "${{GITHUB.WORKSPACE}}"
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: checkooooooooooo
      run: |

        ls -la ${{GITHUB.WORKSPACE}}/app/build/outputs/apk/debug
        echo "###############################################"
        ls -la ${{GITHUB.WORKSPACE}}/app/build/outputs/apk/release

    # - uses: actions/upload-artifact@v3
    #   with:
    #     name: my-first-android-app
    #     path: ${{GITHUB.WORKSPACE}}
